language: python
sudo: required
dist: xenial
python:
  - "3.7"
cache: pip
install:
  - pip install poetry
  - poetry install
script:
  - poetry run pytest --cov-report term-missing --cov-branch --cov=tagfiles tests/
  - poetry run yapf --parallel --diff --recursive .
  - poetry run isort -rc -c .
  - poetry run flake8
after_success:
  - coveralls
