name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyversion }}
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: "${{ runner.os }}-${{ matrix.pyversion }}-poetry-${{ hashFiles('**/poetry.lock') }}"
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          poetry install
      - name: Run tests
        run: poetry run pytest --cov-report=xml --cov=. --cov-branch tests/
      - name: Run lint check
        run: |
          poetry run black --check .
          poetry run isort -c .
          poetry run flake8 .
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -cF python
